"""referrer id

Revision ID: 81fd342d9ea0
Revises: 74b2be586a09
Create Date: 2024-05-23 17:07:02.753052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81fd342d9ea0'
down_revision: Union[str, None] = '74b2be586a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_parent_fkey', 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'categories', ['parent'], ['name'], ondelete='CASCADE')
    op.drop_constraint('products_category_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category'], ['name'], ondelete='CASCADE')
    op.add_column('tg_users', sa.Column('referrer_user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tg_users', 'tg_users', ['referrer_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tg_users', type_='foreignkey')
    op.drop_column('tg_users', 'referrer_user_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_fkey', 'products', 'categories', ['category'], ['name'])
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key('categories_parent_fkey', 'categories', 'categories', ['parent'], ['name'])
    # ### end Alembic commands ###
