"""reviews_status

Revision ID: d7f2f2f65b98
Revises: 2eaee6c73b75
Create Date: 2024-06-26 21:55:55.349397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7f2f2f65b98'
down_revision: Union[str, None] = '2eaee6c73b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    enum_ = postgresql.ENUM('MODERATE', 'PUBLISHED', 'REJECTED', name='reviewsstatuschoices')
    enum_.create(op.get_bind())
    op.add_column(
        'reviews', sa.Column('status', sa.Enum(
            'MODERATE', 'PUBLISHED', 'REJECTED', name='reviewsstatuschoices'
        ), nullable=True, server_default='MODERATE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'status')
    op.execute('DROP TYPE reviewsstatuschoices;')
    # ### end Alembic commands ###
